apiVersion: helm.cattle.io/v1
kind: HelmChart
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  chart: sealed-secrets
  repo: https://charts.bitnami.com/bitnami
  targetNamespace: kube-system
